### PR TITLE
Remove old docs dev build and modernize

### PR DESCRIPTION
**Pull request by willingc**
Addresses #566 

We can remove the "gh-pages" script after all is running on vercel.

### CODE REVIEW

**Review by emeeks — APPROVED** [review]

**Comment by willingc** [comment]
Getting a weird types and transformer error from Parcel. I think it is unhappy with the html file for dev docs.
Screen Shot 2021-12-16 at 9 50

Thoughts? Only found a cryptic old issue on the Parcel site which wasn't very helpful.

**Comment by alexeyraspopov** [comment]
@willingc I'm gonna figure this one out asap

**Comment by alexeyraspopov** [comment]
@willingc, yeah, I know what's up. Parcel relies on some fields in package.json that actually only needed for the library. I know a workaround for this, brb

**Comment by willingc** [comment]
Cool! Feel free to push directly to this PR or create a new PR and I will rebase this on top.

**Comment by alexeyraspopov** [comment]
@willingc, https://github.com/nteract/semiotic/pull/567/commits/7fb8811d93c60a09df9699f70532da95d388baf2 should do the trick. I defined a separate target config for Parcel so it doesn't bother looking into fields like `engines`, `main`, and `types`.

**Comment by willingc** [comment]
Awesome! I'm going to merge. After my call I will update Vercel to display if I am able.

**Pull request merged**
